#include "vmlinux.h"
#include <bpf/bpf_helpers.h>

/* eBPF struct_ops declaration for tcp_congestion_ops */
/* struct minimal_congestion_control_ops implementation would be auto-generated by libbpf */

/* eBPF struct_ops instance: minimal_congestion_control */

SEC("struct_ops/ssthresh")
__u32 ssthresh(__u8* sk) {
    return 16;
}

SEC("struct_ops/cong_avoid")
void cong_avoid(__u8* sk, __u32 ack, __u32 acked) {
}

SEC("struct_ops/set_state")
void set_state(__u8* sk, __u8 new_state) {
}

SEC("struct_ops/cwnd_event")
void cwnd_event(__u8* sk, __u32 ev) {
}

/* eBPF struct_ops declaration for tcp_congestion_ops */
/* struct minimal_congestion_control_ops implementation would be auto-generated by libbpf */

/* eBPF struct_ops instance minimal_congestion_control */
SEC(".struct_ops")
struct tcp_congestion_ops minimal_congestion_control = {
    .ssthresh = (void *)ssthresh,
    .cong_avoid = (void *)cong_avoid,
    .set_state = (void *)set_state,
    .cwnd_event = (void *)cwnd_event,
};

char _license[] SEC("license") = "GPL";